"use strict";
let raing = false;
raing = true;
let idade = 27;
let altura = 1.75;
const nacionalty = 'brasileira';
const colegas = ['lucas', 'fernanda'];
const tecnologias = ['html', 'css'];
const notas = [4, 5, 89];
const lista = ['ye', true, 27];
let idadedaAna = 27;
idadedaAna = '25';
idadedaAna = 25;
let dadosdaApi;
dadosdaApi = 10;
dadosdaApi = true;
dadosdaApi = [15, 7];
dadosdaApi = 'yeyeye';
let curso = 'front';
